name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy API and WebApp
        run: |
          ssh -o StrictHostKeyChecking=no www-data@deploy.fantasy-lcs.com << 'EOF'

          systemctl stop fantasylcsapi.service
          systemctl stop fantasylcswebapp.service

          cd /home/remotedesktop/FantasyLCS.PipelineDeploy
          git pull origin main

          /home/remotedesktop/.dotnet/dotnet publish FantasyLCS.API/FantasyLCS.API.csproj -c Release -o published/FantasyLCS.API
          rsync -avh --delete published/FantasyLCS.API/ /home/remotedesktop/FantasyLCS.API
          systemctl start fantasylcsapi.service

          /home/remotedesktop/.dotnet/dotnet publish FantasyLCS.WebApp/FantasyLCS.WebApp.csproj -c Release -o published/FantasyLCS.WebApp
          rsync -avh --delete published/FantasyLCS.WebApp/ /home/remotedesktop/FantasyLCS.WebApp
          systemctl start fantasylcswebapp.service

          EOF
